
export default {
  SET_TOKEN: 'SET_TOKEN',
  SET_JUMPURL: 'SET_JUMPURL',
  SHOW_LOADING: 'SHOW_LOADING',
  PUT_CACHE_PAGE: 'PUT_CACHE_PAGE',
  REMOVE_CACHE_PAGE: 'REMOVE_CACHE_PAGE',
  ADD_APPLY_LIST: 'ADD_APPLY_LIST',
  SUB_APPLY_GOODS: 'SUB_APPLY_GOODS',
  DEL_APPLY_GOODS: 'DEL_APPLY_GOODS',
  SET_SEARCH_HISTORY: 'SET_SEARCH_HISTORY', // 保存搜索历史
}